# =================
# Release Changelog
# =================

# .github/release.yml
# see https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
    # authors:
    #   - github-actions[bot]

  categories:
    - title: 🚧 Breaking Changes 🏗
      labels:
        # - Semver-Major
        - breaking-change

    - title: 🎂 New Features 🚀
      labels:
        # - Semver-Minor
        - enhancement
        - feature

    - title: 🐛 Bug Fixes 🛠
      labels:
        # - Semver-Patch
        - bug
        - patch

    - title: 🖥 Miscellaneous 📃
      labels:
        - "*"
